events {
    worker_connections 1024;
}

http {
    upstream backend { server backend:8000; }
    upstream customer { server customer:3000; }
    upstream manager { server manager:3001; }

    server {
        listen 80;
        server_name localhost frizura.local;

        location / { proxy_pass http://customer; }
        location /api/ { proxy_pass http://backend; }
    }

    server {
        listen 80;
        server_name admin.localhost admin.frizura.local;
        
        location / { proxy_pass http://manager; }
        location /api/ { proxy_pass http://backend; }
    }
}
